### ISSUE TITLE
PM100USB ThorLabs

### ISSUE THREAD

**Issue by njrebelo** [instrumentkit/InstrumentKit#350]
I am trying to set the wavelenght configuration from my PowerReads, but from your code I don't realaly now how to do it.
I've been doing it manually in the lab

**Comment by scasagrande** [comment]
After opening connection, use the `PM100USB.read` function https://instrumentkit.readthedocs.io/en/latest/apiref/thorlabs.html#instruments.thorlabs.PM100USB.read

**Comment by njrebelo** [comment]
Sorry to only reply now.
My problem is different. I am on the Power configuration, so the PowerMeter is giving me power reads in mW for a given wavelengths. I want to change that wavelenght through the code.
I can already read it.

Many thanks :)

**Comment by njrebelo** [comment]
So I realized this specific to the PM100A, so I add a function to the library with the SCIP command that allows me to do this:

    def wavelenght(self, wav):
        self.sendcmd("CORR:WAV "+str(wav))

Thanks
