### ISSUE TITLE
codecov token not found

### ISSUE THREAD

**Issue by trappitsch** [instrumentkit/InstrumentKit#410]
From the current failure after the merge, it seems like the codecov token was not found:

> Error: Codecov token not found. Please provide Codecov token with -t flag.

I thought this was fine, since PR #409 passed w/o an issue.

@scasagrande: Can you check if the `CODECOV_TOKEN` is set in the repo secrets for actions?

**Comment by scasagrande** [comment]
sorry I did notice that but I'm just a tad swamped

I think codecov made an update that now mandates a token for post-merge builds, I will need to get one
